### PR TITLE
next: Svelte 5

### LINKED ISSUE #7: Arc Text
- https://www.visualcinnamon.com/2015/09/placing-text-on-arcs/

### LINKED ISSUE #112: [Tooltip / Highlight] Radial support
With the recent addition of radial line/area charts, it would be great to support tooltips

- [x] Highlight
  - [x] points
  - [x] lines
  - [x] area
- [ ] modes
  - [x] bisect-x
  - [ ] bisect-y
  - [x] band
  - [x] voronoi
- [x] Manual path (for example Radar with multiple paths)

## Examples
- https://observablehq.com/@analyzer2004/west-coast-weather-from-seattle-to-san-diego
- https://www.amcharts.com/demos/radar-with-date-axis/
- https://www.amcharts.com/demos/solid-gauge/

### LINKED ISSUE #159: Svelte 5 support / migration
Creating an overarching issue to track migrating to Svelte 5.

The plan is for LayerChart 1.x to support Svelte 3, 4, and 5 by not leveraging Svelte 5 specific features like runes and snippets, and 2.x+ will leverage these Svelte 5 specific features.

---
Outstanding Svelte 5 issues:
- ~~[Svelte 5: SVG elements within <slot> fallback not displayed](https://github.com/sveltejs/svelte/issues/11847)~~
  - https://github.com/sveltejs/svelte/pull/11849

---
Issues that should be investigated:
- #158
- https://github.com/techniq/layerchart/issues/291
- https://github.com/techniq/layerchart/issues/292

### LINKED ISSUE #261: Svelte 5: Geo projection transform timing on initial page load
If the page is the initially rendered route, there appears to be an odd timing issue where the `fitGeojson` is calculated too early.  Clicking "reset" will fix the scale/transform, or if you came to the page on a subsequent route.

Note: SSR is currently [disabled](https://github.com/techniq/layerchart/blob/main/packages/layerchart/src/routes/%2Blayout.ts#L5-L6) on the docs, so this is only client side routing.

A video better demonstrates what is happening:

https://github.com/user-attachments/assets/b8723a46-ff87-4a11-afa7-63550e25826e

### LINKED ISSUE #291: Console warnings on client showing div with zero negative height
## Describe Your Error
When mounting any chart I get the following error on the console from the client:

```console
client.js?v=3aef0bf5:2692 [LayerCake] Target div has zero or negative height. Did you forget to set an explicit height in CSS on the container?

client.js?v=8ae4c4ed:2692 [svelte] reactive_declaration_non_reactive_property
A `$:` statement (node_modules/​layercake/​dist/​LayerCake.svelte:225:1) read reactive state that was not visible to the compiler. Updates to this state will not cause the statement to re-run. The behaviour of this code will change if you migrate it to runes mode
```
## Supporting Attachments
image

This error bloats the client console with successful reloads.

## Severity
Annoyance but  can be ignored

## Package versions
node: v22.11.0
bun:  1.1.38
layerchart: "^0.59.5",
"svelte": "^5.5.3",
"svelte-check": "^4.1.1",

### LINKED ISSUE #451: [ForceSimulation] Svelte 5 performance regressions
Sometime during the Svelte 5 releases, performance of the `ForceSimulation` has [deteriorated](https://www.layerchart.com/docs/examples/ForceDisjointGraph).

When the docs were originally [migrated](https://github.com/techniq/layerchart/pull/260) to `svelte@5.0.2` in Oct 2024, [performance](https://techniq-svelte-5-docs.layerchart.pages.dev/docs/examples/ForceDisjointGraph) was consistent (from a user feel) with `svelte@4` ([example](https://regexident-chart-resize-even.layerchart.pages.dev/docs/examples/ForceDisjointGraph)).

There have been some reactivity changes around `5.19.5` that caused some [regressions](https://github.com/techniq/layerchart/issues/384) but not sure if it's related.

There are plans in Svelte to provide better integration with managing state from external sources (ex. d3-force) such as [$state.opaque](https://github.com/sveltejs/svelte/pull/14639), but it was recently determined the ergonomics of this approach were not right.  The maintainers still plan to introduce a solution.

### LINKED ISSUE #456: Svelte 5: Replace `uniqueId` with `$propd.id()`
Svelte `5.20.0` introduced [$props.id()](https://svelte.dev/docs/svelte/$props#$props.id()) which generates an ID that is unique to the current component instance and is consistent between server and client when hydrating a server-rendered component.

### LINKED ISSUE #469: [BarChart] Support radial
- https://observablehq.com/@d3/radial-stacked-bar-chart
- https://observablehq.com/@d3/radial-stacked-bar-chart-ii
- https://observablehq.com/@thetylerwolf/day-17-radial-bar-chart
- https://www.amcharts.com/demos/variable-radius-radar/
- https://observablehq.com/@timlafferty/radial-bar-chart

### LINKED ISSUE #472: Pattern: simplified defintions
In order to support [Canvas](https://github.com/techniq/layerchart/issues/307) and simplify common use cases, we should support

```svelte
<Pattern lines=[{ x2: '100%', class: 'stroke-surface-content' }] width={4} height={4}>
  {#snippet children({ pattern })}
    <rect fill={pattern} />
  {/snippet}
</Pattern>
```

or

```svelte
<Pattern shapes=[{ type: 'rect', x2: '100%', class: 'stroke-surface-content' }] width={4} height={4}>
  {#snippet children({ pattern })}
    <rect fill={pattern} />
  {/snippet}
</Pattern>
```

which translates to:

```svelte
<Pattern width={4} height={4}>
  {#snippet patternContent()}
    <line x2="100%" class="stroke-surface-content" />
  {/snippet}

  {#snippet children({ pattern })}
    <rect fill={pattern} />
  {/snippet}
</Pattern>
```

We would support `line`, `circle`, and other shape types.  Using `<Pattern shapes>` would allow controlling the render/stack order, but would be a more verbose API as well (commonly you only need a single type, or the shapes do not overlap)

Might also be nice to simplify further, similar to [Nivo](https://nivo.rocks/guides/patterns/) ([source](https://github.com/plouc/nivo/tree/master/packages/core/src/components/defs/patterns)) and [Visx](https://airbnb.io/visx/patterns) ([source](https://github.com/airbnb/visx/tree/master/packages/visx-pattern/src/patterns))

### LINKED ISSUE #480: Add `Layer` component to easily switch between Svg, Canvas, and Html layers
Instead of requiring imports for each render context layer...

```svelte
<script>
  import { Canvas, Html, Svg } from 'layerchart';
</script>

<Canvas>...</Canvas>
<Html>...</Html>
<Svg>...</Svg>
```
it would be nice if a single component could be imported with a `type` prop to declare the type of component to use

```svelte
<script>
  import { Layer } from 'layerchart';
</script>

<Layer type="canvas">...</Layer>
<Layer type="html">...</Layer>
<Layer type="svg">...</Layer>
```

The default `type` could probably be `svg` as well.

This is especially helpful for the docs where we allow switching between contexts and currently must do something like this....

```svelte
{@const Component = renderContext === 'canvas' ? Canvas : Svg}

<Component
  this={renderContext === 'canvas' ? Canvas : Svg}
  {...asAny(renderContext === 'canvas' ? props.canvas : props.svg)}
  ...
>
```

### PR DESCRIPTION
**Pull request by huntabyte**
WIP - exploration into what a next-generation API may look like for LayerChart, taking full advantage of Svelte 5.

- [pkg-pr-new comment](https://github.com/techniq/layerchart/pull/458#issuecomment-2738789294)
- [preview](https://huntabyte-next-work.layerchart.pages.dev/) [comment](https://github.com/techniq/layerchart/pull/458#issuecomment-2738789206)

Closes #7
Closes #112
Closes #159
Closes #261
Closes #291
Closes #451
Closes #456
Closes #469
Closes #472
Closes #480

- [x] Add changesets for all new features / breaking changes
- [x] Fix `pnpm check` (svelte-check) failures

---

- [x] Identifier classes on each underlying element for style targeting
- [x] Extended tooltip payload for simplified chart components, such as `BarChart`, `LineChart`, `PieChart`
- [x] Replace `uniqueId` with `$props.id()` and a new `createId` function to create multiple unique ids based off of the single `$props.id()`
- [ ] When scrolling through a page with a chart, if I touch the chart at all it interrupts my scroll. We can likely improve this where only intentional touches are registered/handled
  - Issue: https://github.com/techniq/layerchart/issues/255)
  - See also related: https://github.com/techniq/layerchart/issues/82 / https://github.com/techniq/layerchart/issues/366)
- [x] The `Legend` component should be more composable. Right now if you opt into the included legend via one of the simplfiied charts, you get a bunch of great functionality. The data required for that functionality should be provided via a snippet prop to the `legend` snippet in those components. 
- [ ] When using `<BarChart>` and the resulting Bars end up being `<Rect>`s instead of `<Spline>` the tween configuration doesn't align causing unexpected behavior. Would be nice if we could normalize this so that `BarChart.props.bars.tweened = true` works the same as it does when there aren't all/no rounded corners.
- [ ] ~tickLength specifies how long the tick line itself is, but has no effect on the tickLabel, if this is by design then there should be a way to move the label over as well~ I've since discovered you can accomplish this via `props.xAxis.tickLabelProps.svgProps` but it feels like a lot of work and not the greatest DX for something simple.
- [ ] Labels should wait until their associated chart has finished animating, otherwise you end up with some weird behavior   [example](#ex-A)
- [ ] For improved types/confidence in the APIs, as well as for tree-shaking benefits, perhaps splitting the vastly different chart components into their own top-level component, while only sharing what is necessary to be shared (cartesian, hierarchy, graph, force, geo, etc.). At the moment, regardless if you're using those capabilities or not, you still get them in your bundle.
- [x] ~Determine how to round the radius of specific corners of stacked bar charts.~ using the `series[0].props` did the trick 😃
- [x] Labels have no contextual awareness of the data they may be associated with, for example, if I wanted to make the  labels the same color as the bars (which could be different colors) I can't do so without having to manually build each bar manually. Perhaps similar to the `value` prop exposed on labels, we also expose a `color:` which could either be hard coded or an accessor.
- [ ] What does animating points look like, or at least delaying the display of points when on a line that is currently animating in?
- [ ] What do simplified chart context's look like? There is a lot of useful data built and handled automatically within the `<BarChart>`, `<AreaChart>`, `<LabelChart>`, etc., but the only way to access it is to opt-out of the work it does for you by using the `children` snippet. We should expose that information via a bindable prop as well.
- [ ] Do we _need_ to force the user to manually pass in their own `series` to take advantage of them? What if we just build it for them in absense of one, using the accessor value as the key and then the rest of the data as usual?
- [ ] On mobile when holding down on a chart to see the tooltip, the tooltip is blocked by my thumb, should something be done for this out of the box by default with an escape hatch if necessary? Or should tapping on the chart persist the tooltip if on a touch device?
- [ ] Fix Area stack series tooltip with separate data ([example](http://localhost:3002/docs/components/AreaChart#stack_series_(separate_data))) (recently added)
- [ ] Update BarChart to support stack series with separate data (see AreaChart)
- [ ] Update `Points`/`Labels` to account for x1 scales (i.e grouped by charts) like `Bars`.  ([issue](https://github.com/techniq/layerchart/issues/473))
- [x] Move `selectionState` and `uniqueState` to `@layerstack/svelte-state`
- [ ] Support passing initial series selection
- [ ] Update `BrushContext` to support band scales
- [ ] Determine best use cases between `<ArcChart>` and `<BarChart radial orientation="horizontal">`
  - BarChart
    - Axis support
    - Non-0 start positions
    - Multiple per "track"
    - Stacking? (and when does this become a PieChart if using `stackExpand`)
  - ArcChart
    - Simple for single series
    - Easy/flexible radius control
    - Track color
    - Arc labels
- [ ] Should we consider rendering the axis components under marks (similar to grid)?
  - Would make adding point annotations along x-axis easier (use `aboveMarks` instead of `aboveContext`)
  - How to handle [Axis labels inside bars example](https://huntabyte-next-work.layerchart.pages.dev/docs/components/BarChart#axis_labels_inside_bars) or many [radial](https://huntabyte-next-work.layerchart.pages.dev/docs/components/BarChart#radial_(vertical)) examples. Should we allow controlling the stacking order of each layer/snippet?
- [ ] Remove `asAny()` usage
---

<div id="ex-A">

**Example A**

https://github.com/user-attachments/assets/8c61ba75-738b-4b4e-8c21-54482012a6fd
</div>

---

### Collision Detection
- [ ] [Slower](https://huntabyte-next-work.layerchart.pages.dev/docs/examples/CollisionDetection), less responsive than [before](https://www.layerchart.com/docs/examples/CollisionDetection)

### BrushContext
- [x] Resetting (click within chart) does not appear to be passing original/config domain ([reference](https://github.com/techniq/layerchart/commit/5b95bc95a48e3b050b484bb01ff93ed801c3d21d))
  - Expecting `null` in use case
- [ ] Externally resetting domain not working ([example](https://huntabyte-next-work.layerchart.pages.dev/docs/components/BrushContext#sync_brushes_with_%60bind:xdomain%60))

### BarChart
- [x] Axis labels inside bars (using Labels) not displayed ([example](https://huntabyte-next-work.layerchart.pages.dev/docs/components/BarChart#axis_labels_inside_bars_(using_labels)))

### CODE REVIEW

File: packages/layerchart/src/lib/components/Chart.svelte [hunk 1]
```diff
@@ -1,497 +1,1426 @@
...
-  import { getContext, setContext } from 'svelte';
-
-  export const renderContextKey = Symbol();
-
-  type RenderContext = 'canvas' | 'svg' | 'html';
-
-  /** Get render context.  Useful to conditionally render components based on the render context. */
-  export function getRenderContext() {
-    return getContext<RenderContext>(renderContextKey);
+<script lang="ts" module>
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/Chart.svelte:1]: @techniq I know you've mentioned in another issue about replacing LayerCake accessors with LayerCharts accessors. I think it's a great idea so we don't have a weird mixture of the two, but I haven't done it yet. I mostly tried to keep this file an exact port of LayerCake + LayerChart v1's `<Chart>` component.

This file feels really messy and bloated, but I will leave that to the expert (you) to assess/simplify, as my attempts resulted in various things breaking. 😃

File: packages/layerchart/src/lib/components/Chart.svelte [hunk 2]
```diff
@@ -1,497 +1,1426 @@
...
+    /**
+     * A bindable reference to the root container element.
+     */
+    ref?: HTMLElement;
+
+    /**
+     * If `data` is not a flat array of objects and you want to use any of the scales, set a flat
+     * version of the data via the `flatData` prop.
+     */
+    data?: T[] | readonly T[] | HierarchyNode<T> | SankeyGraph<any, any>;
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/Chart.svelte:255]: This is one of the reasons I think it makes sense to split these vastly different charts into their own components. These types are so different that it makes keeping types safe throughout the project near impossible.

File: packages/layerchart/src/lib/components/Chart.svelte [hunk 3]
```diff
@@ -1,497 +1,1426 @@
...
+      [
+        {
+          context: ChartContextValue<T>;
+          transformContext: TransformContextValue;
+          geoContext: GeoContextValue;
+          tooltipContext: TooltipContextValue;
+          brushContext: BrushContextValue;
+        },
+      ]
+    >;
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/Chart.svelte:668]: Rather than exposing 300 individual snippet props for all the various things one may need, we provide the reactive context objects to access any of those properties.

File: packages/layerchart/src/lib/components/Chart.svelte [hunk 4]
```diff
@@ -1,497 +1,1426 @@
...
+
+    /**
+     * A bindable reference to the chart context.
+     */
+    context?: ChartContextValue<T>;
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/Chart.svelte:673]: This is useful for getting a reference to the chart's context via the simplified charts like `<BarChart bind:context>` where you don't want to override all the existing children, but still want to access the context.

File: packages/layerchart/src/lib/components/tooltip/tooltipMetaContext.ts [hunk 5]
```diff
@@ -0,0 +1,252 @@
+// Additional meta data that can be set by the various simplified chart components
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/tooltip/tooltipMetaContext.ts:1]: This is a big missing piece with tooltip data and simplified charts that use series. It provides the tooltip context/snippet with a lot more useful data to render out more complex tooltips when working with series data.

File: packages/layerchart/src/lib/components/MarkerWrapper.svelte [hunk 6]
```diff
@@ -0,0 +1,35 @@
+<script lang="ts" module>
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/MarkerWrapper.svelte:1]: This component simplifies the various conditionals everywhere markers are used.

File: packages/layerchart/src/lib/stores/selectionState.svelte.ts [hunk 7]
```diff
@@ -0,0 +1,116 @@
+import { uniqueState } from './uniqueState.svelte.js';
```
Comment (huntabyte) [inline packages/layerchart/src/lib/stores/selectionState.svelte.ts:1]: Ported from layerstack/utils to use Svelte 5 reactivity instead of stores.

File: packages/layerchart/src/lib/stores/uniqueState.svelte.ts [hunk 8]
```diff
@@ -0,0 +1,34 @@
+import { SvelteSet } from 'svelte/reactivity';
```
Comment (huntabyte) [inline packages/layerchart/src/lib/stores/uniqueState.svelte.ts:1]: Ported from layerstack/utils to use Svelte 5 reactivity instead of stores.

File: packages/layerchart/src/lib/utils/afterTick.ts [hunk 9]
```diff
@@ -0,0 +1,9 @@
+import { tick } from 'svelte';
+
+/**
+ * Executes a callback function after the next DOM update.
+ * @param cb Callback function to be executed after the next DOM update
+ */
+export function afterTick(cb: () => void) {
```
Comment (huntabyte) [inline packages/layerchart/src/lib/utils/afterTick.ts:7]: I love this util and use it in almost every project :)

File: packages/layerchart/src/lib/components/charts/AreaChart.svelte [hunk 10]
```diff
@@ -264,121 +266,115 @@
...
+    get stackSeries() {
+      return stackSeries;
+    },
+    get visibleSeries() {
+      return visibleSeries;
+    },
+  });
 </script>
 
+<!-- svelte-ignore ownership_invalid_binding -->
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/charts/AreaChart.svelte:289]: Svelte is excessive with these warnings, we know what we're doing :)

File: packages/layerchart/src/lib/components/Labels.svelte [hunk 11]
```diff
@@ -1,56 +1,128 @@
...
+     */
+    value?: Accessor<T>;
+
+    /**
+     * The fill color of the label, which can either be a string or an accessor function
+     * that returns a valid `fill` color value.
+     *
+     * The accessor is useful for dynamic fill colors based on the data the label represents.
+     */
+    fill?: string | Accessor<T>;
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/Labels.svelte:26]: I found myself needing this to apply dynamic label fill based on the data in the `<BarChart>`. Perhaps we could simplify this further and make the top level `labels` prop of the simplified charts either `boolean | Snippet | Accessor` so all the props could be handled dynamically if desired? Just thoughts!

File: packages/layerchart/src/lib/components/Chart.svelte (hunk 2 above)
Comment (techniq) [reply packages/layerchart/src/lib/components/Chart.svelte:255]: I think there are 2 improvements.

1. While I might be overlooking a use case, but only accept `data` as `T[]` and passing hierarchy or graph data directly to the applicable layout component makes more sense.  Either `<Pack {data}>` / `<Dagre {data}>` or `<Pack {hierarchy}>` / `<Dagre {graph}>` (leaning towards the later)
2. Adding simplified charts for hierarchy/graph/force/geo.  Tracking as part of https://github.com/techniq/layerchart/issues/246 (might be worth itemizing this issue now)

File: packages/layerchart/src/lib/components/Chart.svelte (hunk 3 above)
Comment (techniq) [reply packages/layerchart/src/lib/components/Chart.svelte:668]: If we can orchestrate the change (upstream or potentially circular deps), I'm not against consolidating all the contexts into the primary `context` object with properties (`context.transform`, `context.tooltip`, etc).  The iterative approach of adding these as well as needing to subscribe to stores kept these more separate than they probably should be.

Also working through [cartesian transforms](https://github.com/techniq/layerchart/issues/366) and integrating [bounds](https://github.com/techniq/layerchart/blob/main/packages/layerchart/src/lib/components/Bounds.svelte) ([partition](https://www.layerchart.com/docs/examples/Partition), [treemap](https://www.layerchart.com/docs/examples/Treemap), [sunburst](https://www.layerchart.com/docs/examples/Sunburst) drilldown) might be simpler / clearer.

File: packages/layerchart/src/lib/components/tooltip/tooltipMetaContext.ts [hunk 12]
```diff
@@ -0,0 +1,263 @@
...
+  value?: any;
+  keyAccessor?: Accessor<any>;
+  valueAccessor?: Accessor<any>;
+  labelAccessor?: Accessor<any>;
+  colorAccessor?: Accessor<any>;
+  chartType?: SimplifiedChartType;
+  payload: any;
+  rawSeriesData?: SeriesData<any, any>;
+  formatter?: FormatType;
+};
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/tooltip/tooltipMetaContext.ts:76]: @techniq this is something I'd like to bikeshed/get your thoughts on and try to remain consistent across the lib. What is a `name` vs what is a `label`, etc.

File: packages/layerchart/src/lib/components/layout/Layer.svelte [hunk 13]
```diff
@@ -0,0 +1,37 @@
+<script lang="ts" module>
+  import type { ComponentProps } from 'svelte';
+
+  export type LayerProps<T extends 'canvas' | 'html' | 'svg' = 'svg'> = {
+    /** Type of layer (Canvas, Svg, or Html)
+     *
+     * @default 'svg'
+     */
+    type?: T;
```
Comment (huntabyte) [inline packages/layerchart/src/lib/components/layout/Layer.svelte:9]: The safest way is to make this a required prop

**Review by techniq — APPROVED** [review]
@huntabyte amazing work!  Releasing as `2.0.0-next.2` and we'll continue to iterate as we move towards a `2.0.0` release
